[package]
name    = "db"
version = "0.1.0"
authors = ["Chinmay Kulkarni <chnm.kulkarni@gmail.com>",
           "Ryan Stutsman <stutsman@cs.utah.edu>"]
license = "MIT"

[lib]
name = "db"
path = "src/lib.rs"

[[bin]]
name = "server"
path = "src/bin/server.rs"

[[bin]]
name = "client"
path = "src/bin/client.rs"

[[bin]]
name = "ext_bench"
path = "src/bin/ext_bench.rs"

[dependencies]
log        = "0.3"
rand       = "0.3"
time       = "0.1"
spin       = "0.4" # Consider using parking lot?
bytes      = "0.4"
env_logger = "0.3"
libloading = "0.3"
sandstorm  = {path = "../sandstorm"}
e2d2       = {path = "../net/framework"}
